name: build debug

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.version.outputs.version_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get short Git hash
        id: version
        run: |
          SHORT_GIT_SHA=$(git rev-parse --short HEAD)
          echo "version_name=ci-${SHORT_GIT_SHA}" >> $GITHUB_OUTPUT

  build-debug:
    needs: get-version
    uses: ./.github/workflows/build.yml
    with:
      version_name: ${{ needs.get-version.outputs.version_name }}
      version_code: ${{ github.run_number }}
      build_type: debug