name: build debug

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    outputs:
      apk_path: ${{ steps.build.outputs.apk_path }}
      bundle_path: ${{ steps.build.outputs.bundle_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Print secrets
        run: |
          mkdir secrets
          echo '${{ secrets.TOPSECRET }}' > secrets/topsecret.txt
          echo '${{TOPSECRET }}' > secrets/env_topsecret.txt
          ls -la secrets
          cat secrets/*.txt        
